AWSTemplateFormatVersion: 2010-09-09
Description: 'Sample CF for Secure SSM'

Resources:
  AnotherSampleSecureSSM:
    Type: RP::SSM::SecureParameter
    Properties:
      Description: "Sample secure ssm"
      Name: "/sample/secure/ssm"
      Value: "secret"
      KeyId: "alias/aws/ssm"
      Tags:
        - "key1": "value1"
        - "key2": "value2"