AWSTemplateFormatVersion: 2010-09-09
Description: 'Sample CF for Secure SSM'

Resources:
  SampleSecureSSMParam:
    Type: RP::SSM::SecureParameter
    Properties:
      Description: "Sample secure ssm"
      Name: "/sample/secure/ssm"
      Value: "another value"
      KeyId: "alias/aws/ssm"
      Tags:
        - Key: "key"
          Value: "value"