package resource

import "github.com/aws-cloudformation/cloudformation-cli-go-plugin/cfn/encoding"

/*
This file is autogenerated, do not edit;
changes will be undone by the next 'generate' command.

Updates to this type are made my editing the schema file
and executing the 'generate' command
*/

// Model is autogenerated from the json schema
type Model struct {
	AllowedPattern *encoding.String `json:"AllowedPattern,omitempty"`
	Description    *encoding.String `json:"Description,omitempty"`
	Name           *encoding.String `json:"Name,omitempty"`
	Policies       *encoding.String `json:"Policies,omitempty"`
	Tier           *encoding.String `json:"Tier,omitempty"`
	Value          *encoding.String `json:"Value,omitempty"`
	Tags           []Tag            `json:"Tags,omitempty"`
}

// Tag is autogenerated from the json schema
type Tag struct {
	Key   *encoding.String
	Value *encoding.String
}
