package resource

/*
This file is autogenerated, do not edit;
changes will be undone by the next 'generate' command.

Updates to this type are made my editing the schema file
and executing the 'generate' command
*/

// Model is autogenerated from the json schema
type Model struct {
	AllowedPattern *string `json:"AllowedPattern,omitempty"`
	Description    *string `json:"Description,omitempty"`
	Name           *string `json:"Name,omitempty"`
	KeyId          *string `json:"KeyId,omitempty"`
	Policies       *string `json:"Policies,omitempty"`
	Tier           *string `json:"Tier,omitempty"`
	Value          *string `json:"Value,omitempty"`
	Tags           []Tag   `json:"Tags,omitempty"`
}

// Tag is autogenerated from the json schema
type Tag struct {
	Key   *string `json:",omitempty"`
	Value *string `json:",omitempty"`
}
