name: aws-cloudformation-resource-providers-ssm-secure-param

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build ${{ matrix.target_os }}_${{ matrix.target_arch }} binaries
    runs-on: ${{ matrix.os }}
    env:
      GOVER: 1.13.7
      GOOS: ${{ matrix.target_os }}
      GOARCH: ${{ matrix.target_arch }}
      GOPROXY: https://proxy.golang.org,direct
      GOLANGCI_LINT_VER: v1.23.3
    strategy:
      matrix:
        os: [ubuntu-latest]
        target_arch: [amd64]
    steps:
      - name: Set up Go ${{ env.GOVER }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GOVER }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Install golangci-lint ${{ env.GOLANGCI_LINT_VER }}
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "${{ env.GOROOT }}/bin" "${{ env.GOLANGCI_LINT_VER }}"
      - name: Run make lint
        run: make lint
      - name: Run make test
        run: make test